
name: Get Latest Realease

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: fossapp
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "chronis10/fossbot-app"
          type: "stable"
      - name: "Print result"
        run: |
          echo "id: ${{ steps.fossapp.outputs.release }}"
