name: Build Physical Robot image

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: fossapp
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "chronis10/fossbot-app"
          type: "stable"
      - name: "Print result"
        run: |
          echo "id: ${{ steps.fossapp.outputs.release }}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push ARM image
        uses: docker/build-push-action@v2
        
        with:       
          context: blockly_server
          file: blockly_server/Dockerfile_PHYS
          platforms: linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fossbot_blockly_phy:${{steps.fossapp.outputs.release }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fossbot_blockly_phy:latest
