name: Build Ubuntu app

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockly_server
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Env var
          run: export PYTHON_CONFIGURE_OPTS="--enable-shared" 
        - name: pip install dependencies basic
          run: pip install -r requirements.txt
        - name: pip install dependencies extra
          run: pip install -r requirements_app.txt
        - name: Install pyinstaller
          run: pip install pyinstaller
        - name: compile GUI for Ubuntu
          run: pyinstaller app.spec
        - name: see files
          run: |
            cd dist/
            ls
            pwd
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: ubuntu-fossbot
            path: /home/runner/work/fossbot-app/fossbot-app/blockly_server/dist
