name: Build Windows app

on: [workflow_dispatch]

jobs:
  build:
    runs-on: Windows-latest
    defaults:
      run:
        working-directory: blockly_server
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: pip install dependencies basic
          run: pip install -r requirements.txt
        - name: pip install dependencies extra
          run: pip install -r requirements_app.txt
        - name: Install pyinstaller
          run: pip install pyinstaller
        - name: compile GUI for Windows OS
          run: pyinstaller app.spec
        - name: copy lib
          run: cp -r ../lib dist/          
        - name: see files
          run: |
            cd dist
            dir
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: windows-fossbot
            path: D:\\a\\fossbot-app\\fossbot-app\\blockly_server\\dist
